import { IncidentType, WeightedKeyword } from "../types";

export const englishKeywords: Record<IncidentType, WeightedKeyword[]> = {
  [IncidentType.JAM]: [
    // Primary — unambiguous traffic congestion terms
    { word: "traffic jam", weight: 1.0 },
    { word: "gridlock", weight: 1.0 },
    { word: "standstill", weight: 1.0 },
    { word: "bumper to bumper", weight: 1.0 },
    { word: "snarled", weight: 0.9 },
    { word: "snarl", weight: 0.9 },
    { word: "snarled up", weight: 1.0 },
    { word: "choked", weight: 0.9 },
    { word: "clogged", weight: 0.9 },
    { word: "crawling", weight: 0.8 },
    { word: "slow moving", weight: 0.8 },
    { word: "slow-moving", weight: 0.8 },
    { word: "heavy traffic", weight: 0.9 },
    { word: "severe congestion", weight: 1.0 },
    { word: "congestion", weight: 0.8 },
    { word: "congested", weight: 0.8 },
    // Secondary — imply delay without specifying cause
    { word: "long queue", weight: 0.6 },
    { word: "massive queue", weight: 0.7 },
    { word: "vehicle queue", weight: 0.6 },
    { word: "tailback", weight: 0.7 },
    { word: "backup", weight: 0.5 },
    { word: "hold-up", weight: 0.6 },
    { word: "holdup", weight: 0.6 },
    { word: "delay", weight: 0.5 },
    { word: "delayed", weight: 0.5 },
    { word: "slow", weight: 0.3 },
    { word: "blocked", weight: 0.5 },
    { word: "bottleneck", weight: 0.7 },
  ],

  [IncidentType.ACCIDENT]: [
    // Primary
    { word: "accident", weight: 1.0 },
    { word: "collision", weight: 1.0 },
    { word: "crash", weight: 1.0 },
    { word: "road accident", weight: 1.0 },
    { word: "vehicle accident", weight: 1.0 },
    { word: "fatal accident", weight: 1.0 },
    { word: "hit and run", weight: 1.0 },
    { word: "hit-and-run", weight: 1.0 },
    { word: "overturned", weight: 0.9 },
    { word: "overturned vehicle", weight: 1.0 },
    { word: "bus overturned", weight: 1.0 },
    { word: "truck overturned", weight: 1.0 },
    { word: "head-on", weight: 0.9 },
    { word: "head on collision", weight: 1.0 },
    { word: "multi vehicle", weight: 0.9 },
    { word: "pile up", weight: 1.0 },
    { word: "pileup", weight: 1.0 },
    // Secondary
    { word: "injured", weight: 0.6 },
    { word: "casualties", weight: 0.6 },
    { word: "dead", weight: 0.5 },
    { word: "killed", weight: 0.5 },
    { word: "hospitalised", weight: 0.5 },
    { word: "hospitalized", weight: 0.5 },
    { word: "skidded", weight: 0.6 },
    { word: "skid", weight: 0.5 },
    { word: "rammed", weight: 0.7 },
    { word: "smashed", weight: 0.6 },
    { word: "rescue", weight: 0.3 },
  ],

  [IncidentType.SIGNAL]: [
    // Primary
    { word: "signal failure", weight: 1.0 },
    { word: "traffic signal", weight: 0.9 },
    { word: "traffic light", weight: 0.9 },
    { word: "signal out", weight: 1.0 },
    { word: "signal down", weight: 1.0 },
    { word: "signal malfunction", weight: 1.0 },
    { word: "traffic signal failure", weight: 1.0 },
    { word: "signal not working", weight: 1.0 },
    { word: "lights out", weight: 0.7 },
    { word: "traffic police managing", weight: 0.8 },
    { word: "manual signalling", weight: 0.9 },
    { word: "manual signal", weight: 0.9 },
    // Secondary
    { word: "signal", weight: 0.4 },
    { word: "junction", weight: 0.3 },
    { word: "crossing", weight: 0.3 },
    { word: "intersection", weight: 0.3 },
    { word: "traffic point", weight: 0.5 },
    { word: "no signal", weight: 0.7 },
    { word: "dark signal", weight: 0.7 },
  ],

  [IncidentType.FLOODING]: [
    // Primary
    { word: "waterlogging", weight: 1.0 },
    { word: "waterlogged", weight: 1.0 },
    { word: "flooded", weight: 1.0 },
    { word: "flooding", weight: 1.0 },
    { word: "flood", weight: 0.9 },
    { word: "submerged", weight: 1.0 },
    { word: "inundated", weight: 1.0 },
    { word: "knee deep water", weight: 1.0 },
    { word: "knee-deep water", weight: 1.0 },
    { word: "ankle deep water", weight: 1.0 },
    { word: "waist deep", weight: 1.0 },
    { word: "road under water", weight: 1.0 },
    { word: "roads under water", weight: 1.0 },
    { word: "heavy rain", weight: 0.6 },
    { word: "rainwater accumulation", weight: 0.9 },
    { word: "drainage failure", weight: 0.9 },
    { word: "pump failure", weight: 0.8 },
    // Secondary
    { word: "rain", weight: 0.3 },
    { word: "rainfall", weight: 0.3 },
    { word: "puddle", weight: 0.4 },
    { word: "water on road", weight: 0.7 },
    { word: "wet roads", weight: 0.4 },
  ],

  [IncidentType.DIVERSION]: [
    // Primary
    { word: "diversion", weight: 1.0 },
    { word: "diverted", weight: 1.0 },
    { word: "route change", weight: 0.9 },
    { word: "alternate route", weight: 0.9 },
    { word: "alternative route", weight: 0.9 },
    { word: "road closed", weight: 1.0 },
    { word: "road closure", weight: 1.0 },
    { word: "lane closed", weight: 0.9 },
    { word: "lane closure", weight: 0.9 },
    { word: "blocked road", weight: 0.9 },
    { word: "road block", weight: 0.9 },
    { word: "barricade", weight: 0.8 },
    { word: "barricaded", weight: 0.8 },
    { word: "section closed", weight: 0.9 },
    { word: "detour", weight: 1.0 },
    { word: "traffic diversion", weight: 1.0 },
    { word: "bus route changed", weight: 0.9 },
    { word: "bus diverted", weight: 0.9 },
    { word: "vehicles diverted", weight: 1.0 },
    { word: "vip movement", weight: 0.8 },
    { word: "rally", weight: 0.6 },
    { word: "procession", weight: 0.7 },
    { word: "protest", weight: 0.5 },
    { word: "bandh", weight: 0.8 },
    // Secondary
    { word: "closed", weight: 0.4 },
    { word: "shutdown", weight: 0.4 },
    { word: "restricted", weight: 0.5 },
    { word: "no entry", weight: 0.7 },
    { word: "one way", weight: 0.4 },
  ],

  [IncidentType.UNKNOWN]: [],
};
